
export const MOCK_USERS = [
    { "name": "James Carter", "motto": "Did a thing. Logged it." },
    { "name": "Michael Brooks", "motto": "Progress but make it quiet." },
    { "name": "David Nguyen", "motto": "Checked in. Still alive." },
    { "name": "Daniel Kim", "motto": "We call that a win." },
    { "name": "Chris Johnson", "motto": "Future me can’t complain." },
    { "name": "Matthew Patel", "motto": "One checkbox at a time." },
    { "name": "Andrew Garcia", "motto": "It happened. Allegedly." },
    { "name": "John Martinez", "motto": "Still counts." },
    { "name": "Ryan Lee", "motto": "Minimum effort, maximum honesty." },
    { "name": "Kevin Chen", "motto": "The log knows the truth." },
    { "name": "Brian Wilson", "motto": "Done is done." },
    { "name": "Jason Park", "motto": "No story. Just data." },
    { "name": "Justin Taylor", "motto": "Checked. Next." },
    { "name": "Eric Huang", "motto": "Somehow still consistent." },
    { "name": "Mark Thompson", "motto": "We move." },
    { "name": "Alex Rivera", "motto": "Recorded for legal reasons." },
    { "name": "Tom Anderson", "motto": "Boring. Reliable." },
    { "name": "Nick Roberts", "motto": "It is what it is." },
    { "name": "Josh Miller", "motto": "No drama. Just logs." },
    { "name": "Ethan Walker", "motto": "Another brick in the wall." },
    { "name": "Marcus Johnson", "motto": "Still showing up." },
    { "name": "Jamal Harris", "motto": "We try again tomorrow." },
    { "name": "Darius Coleman", "motto": "Better than nothing." },
    { "name": "Tyrone Mitchell", "motto": "Documented and moving on." },
    { "name": "Malik Robinson", "motto": "Quiet effort detected." },
    { "name": "DeShawn Parker", "motto": "No excuses stored here." },
    { "name": "Andre Williams", "motto": "The numbers don’t care." },
    { "name": "Terrence Brown", "motto": "Still in the game." },
    { "name": "Caleb Wright", "motto": "Logged. Life continues." },
    { "name": "Jordan Scott", "motto": "Consistency but low-key." },
    { "name": "Jose Ramirez", "motto": "The spreadsheet remembers." },
    { "name": "Luis Hernandez", "motto": "Checked the box. Walked away." },
    { "name": "Carlos Mendoza", "motto": "No witnesses, only records." },
    { "name": "Miguel Alvarez", "motto": "This counts, right?" },
    { "name": "Javier Torres", "motto": "Documented for my future self." },
    { "name": "Diego Flores", "motto": "Boring progress is still progress." },
    { "name": "Fernando Cruz", "motto": "The system sees all." },
    { "name": "Roberto Castillo", "motto": "Logged and emotionally detached." },
    { "name": "Ricardo Vega", "motto": "No vibes, just data." },
    { "name": "Antonio Morales", "motto": "Evidence-based living." },
    { "name": "Steven Moore", "motto": "The app has receipts." },
    { "name": "Peter Young", "motto": "I was here." },
    { "name": "Lucas Turner", "motto": "Nothing fancy happened." },
    { "name": "Noah Bennett", "motto": "Checked in, checked out." },
    { "name": "Nathan Collins", "motto": "Another extremely normal day." },
    { "name": "Henry Adams", "motto": "Recorded like a responsible adult." },
    { "name": "Adam Fisher", "motto": "No opinions. Just entries." },
    { "name": "Samuel Reed", "motto": "The log is undefeated." },
    { "name": "Benjamin Price", "motto": "History is written by checkmarks." },
    { "name": "Lucas Morgan", "motto": "Still building the paper trail." },
    { "name": "Daniel Wright", "motto": "Walk by faith, log by habit." },
    { "name": "Joshua Green", "motto": "Small steps still count." },
    { "name": "Isaac Turner", "motto": "Stay steady." },
    { "name": "Elijah Brooks", "motto": "Do what you can today." },
    { "name": "Aaron Cooper", "motto": "One day at a time." },
    { "name": "Jacob Simmons", "motto": "Trust the process (annoying but true)." },
    { "name": "Emily Parker", "motto": "Tiny progress is still progress." },
    { "name": "Sarah Mitchell", "motto": "Soft consistency." },
    { "name": "Jessica Liu", "motto": "I showed up. That’s enough." },
    { "name": "Ashley Kim", "motto": "Doing my best-ish." },
    { "name": "Megan O'Connor", "motto": "Gentle but consistent." },
    { "name": "Amanda Rodriguez", "motto": "No pressure. Just records." },
    { "name": "Rachel Stein", "motto": "Small boxes. Big energy." },
    { "name": "Lauren Chen", "motto": "Logged and moving on." },
    { "name": "Hannah Brooks", "motto": "Quiet progress club." },
    { "name": "Olivia Martinez", "motto": "I came, I logged, I left." },
    { "name": "Grace Kim", "motto": "Be consistent, not dramatic." },
    { "name": "Sophia Nguyen", "motto": "Done is beautiful." },
    { "name": "Chloe Park", "motto": "Another square checked." },
    { "name": "Isabella Rossi", "motto": "Minimal effort, maximal honesty." },
    { "name": "Natalie Cohen", "motto": "The record is kind." },
    { "name": "Priya Shah", "motto": "Slowly but actually." },
    { "name": "Aisha Johnson", "motto": "Still trying, still logging." },
    { "name": "Maria Lopez", "motto": "No stories, just facts." },
    { "name": "Yuki Tanaka", "motto": "Quietly consistent." },
    { "name": "Emma Wilson", "motto": "Progress, but chill." }
];
